import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { UserProvider } from '@/components/UserProvider';
import { Toaster } from "@/components/ui/sonner"


export const metadata: Metadata = {
  title: "GoStock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <UserProvider>
        <body className="font-sans md:py-0 bg-[#F5F7F9] h-screen flex md:gap-2 flex-col md:flex-row py-16 ">
          <div className="w-[300px] md:block hidden">
            <Sidebar/>
          </div>
          <div className="flex-grow md:block hidden">
            <Header />
            {children}
          </div>
          <Toaster />
        </body>
      </UserProvider>
    </html>
  );
}
